# Site
name: "Transición energética en México"
title: "Transición energética en México"
description: "Transición energética en México"
meta_description: "Transición energética en México"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'transicionenergeticaenmexico@gmail.com'
#google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  sandra:
    name: Sandra Guzmán
    display_name: Sandra Guzmán
    gravatar: 
    email: 
    web: 
    twitter: 
    description: "Founder and Global Agenda Coordinator, GFLAC and consultant for the Secretariat of the UNFCCC."
  eluniversal:
    name: Periodico "El Universal"
    display_name: Periodico "El Universal"
    gravatar: 
    email: 
    web: 
    twitter: 
    description: 
  samedwards:
    name: Sam Edwards
    display_name: Sam Edwards
    gravatar: 
    email: 
    web: 
    twitter: 
    description: "Sam Edwards is a journalist based in Mexico. His work has appeared in The Guardian, The Nation, and Foreign Affairs, among others."
  climatetransparency:
    name: Climate Transparency Org.
    display_name: Climate Transparency Org.
    gravatar: 
    email: 
    web: 
    twitter: 
    description: "Climate Transparency is a global partnership with a shared mission to stimulate a ‘race to the top’ in G20 climate action and to shift investments towards zero carbon technologies through enhanced transparency."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge